import Event from "@/database/event.model";
import connectDB from "@/lib/mongodb";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        await connectDB();

        const formData = await req.formData();

        // Define required fields (slug is auto-generated by the model's pre-save hook)
        const fields = ['title', 'description', 'overview', 'image', 'venue', 'location', 'date', 'time', 'mode', 'audience', 'organizer'];

        // Validate required fields
        const missingFields = fields.filter(field => !formData.has(field) || !formData.get(field));
        if (missingFields.length > 0) {
            return NextResponse.json(
                { message: `Missing required fields: ${missingFields.join(', ')}` },
                { status: 400 }
            );
        }

        // Whitelist and extract allowed fields
        const eventData: Record<string, unknown> = {};
        fields.forEach(field => {
            const value = formData.get(field);
            if (value !== null) {
                eventData[field] = value;
            }
        });

        // Parse tags and agenda from JSON strings
        const rawTags = formData.get('tags');
        const rawAgenda = formData.get('agenda');

        let tags: string[] = [];
        let agenda: string[] = [];

        try {
            tags = rawTags ? JSON.parse(String(rawTags)) : [];
            agenda = rawAgenda ? JSON.parse(String(rawAgenda)) : [];
        } catch {
            return NextResponse.json({ message: 'Invalid JSON format for tags or agenda' }, { status: 400 });
        }

        // Create event (slug will be auto-generated by the model)
        const createdEvent = await Event.create({
            ...eventData,
            tags,
            agenda
        });

        return NextResponse.json({
            message: 'Event created successfully',
            event: createdEvent
        }, { status: 201 });
    } catch (e) {
        console.error('Event creation error:', e);
        return NextResponse.json({
            message: 'Event creation failed',
            error: e instanceof Error ? e.message : 'Unknown error'
        }, { status: 500 });
    }
}

export async function GET() {
    try {
        await connectDB();

        const events = await Event.find().sort({ createdAt: -1 });

        return NextResponse.json({
            message: 'Events fetched successfully',
            events
        }, { status: 200 });
    } catch (e) {
        return NextResponse.json({
            message: 'Event fetching failed',
            error: e instanceof Error ? e.message : 'Unknown error'
        }, { status: 500 });
    }
}